# Generated by Django 5.1.4 on 2025-01-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alphabet_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.letter')),
            ],
        ),
    ]
