# Generated by Django 5.1.4 on 2025-01-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.letter')),
            ],
        ),
    ]
