# Generated by Django 5.1.4 on 2025-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_letterimage_audio_letterimage_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterimage',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='letterimage',
            name='character_image',
        ),
        migrations.AddField(
            model_name='letter',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='letter',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
    ]
