# Generated by Django 5.1.4 on 2025-01-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_letterimage_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='character_image',
            field=models.ImageField(blank=True, default='character_images/default.png', null=True, upload_to='character_images/'),
        ),
    ]
