# Generated by Django 5.1.4 on 2025-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_letter_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='audio',
        ),
    ]
