# Generated by Django 5.1.4 on 2025-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_testprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameimage',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
